# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.xfx_api import XfxApi  # noqa: E501
from swagger_client.rest import ApiException


class TestXfxApi(unittest.TestCase):
    """XfxApi unit test stubs"""

    def setUp(self):
        self.api = XfxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_browse_files(self):
        """Test case for browse_files

        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        """
        pass

    def test_download_file(self):
        """Test case for download_file

        """
        pass

    def test_rename_file(self):
        """Test case for rename_file

        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
